### ISSUE TITLE
tracker issue before 2.x release

### ISSUE THREAD

**Issue by fkooman** [fkooman/php-remote-storage#77]
I did a bunch of refactoring and cleaning up, but there is more to do, it is hard to create a list now as that list will only grow when going through the code :-)

Just a start:

* [ ] update documentation, match reality
  * [ ] document how to set up Apache|Nginx + php-fpm on modern Debian/Ubuntu
* [ ] remove fkooman/secookie dependency (native PHP sessions are good enough for php-remote-storage)
* [ ] remove twig dependency (PHP *is* a template language)
* [ ] remove yaml dependency, either use PHP directly or ini format
* [ ] make config parsing more robust
* [ ] store users in database, not in config file
* [ ] enable foreign keys for SQLite (disabled by default)
* [ ] figure out whether CORS headers are all set correctly now
* [ ] provide DEB and RPM packages for easy installation

**Comment by fkooman** [comment]
@raucao

**Comment by raucao** [comment]
Great! :clap: 

Some of these seem more like feature wishes than necessities to me.

> * make config parsing more robust
> * store users in database, not in config file
> * enable foreign keys for SQLite (disabled by default)

These are all nice improvements, but couldn't they be made in a 2.1 version?

> * provide DEB and RPM packages for easy installation

The package would use the actual tagged release, so I think these arguably great (yet external) features would come after the 2.0 release anyway, no?

**Comment by fkooman** [comment]
> Some of these seem more like feature wishes than necessities to me.

Yeah, sure.

Tightening static code analysis tools also helped a lot in improving code, this was done in last commit... could be that stuff was broken by improving code, I test with `localhost`. The sync seems broken somehow, but I am not sure why. My old favorite drinks are gone. They are still on disk, didn't take time to debug.

**Comment by fkooman** [comment]
Interesting PHP issue: if you name your drink e.g. '12345' everything will break because of [this](https://lobste.rs/s/t8cdqz/php_frankenstein_arrays#c_lceuqy).
